"use client";

import { FormEvent, useMemo, useState } from "react";
import { CalendarDays, Camera, Gift, Heart, Home, Info, Mail, Menu, MessageCircle, Newspaper, PartyPopper, Send, Star, Users, ChevronRight, BadgeDollarSign, Sparkles, Images, Smile, HandHeart } from "lucide-react";

type Tab = "home"|"events"|"book"|"messages"|"more";
type View = Tab|"about"|"media"|"reviews"|"sponsor"|"bored"|"pricing"|"gallery";
const EMAIL="Hello@thesiouxvillegrinch.com";
const SITE="https://thesiouxvillegrinch.com";

function Logo(){return <img className="real-logo" src={`${SITE}/fulllogo2.jpg`} alt="The Siouxville Grinch"/>}
function HeroCollage(){return <img src={`${SITE}/grinchcollage.jpg`} alt="The Siouxville Grinch appearances"/>}
function mail(subject:string, body:string){window.location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}

function HomeScreen({go}:{go:(v:View)=>void}){return <div className="screen-content">
  <section className="logo-card"><Logo/><div className="confetti">🍁 🐝 🍁 🐝 🍁</div></section>
  <section className="hero-copy"><span className="eyebrow">WELCOME TO SIOUXVILLE</span><h1>Holiday mischief.<br/><em>Now in your pocket.</em></h1><p>Family events, business promotions, parades, charity partnerships and custom holiday experiences — with the festive chaos of The Siouxville Grinch.</p></section>
  <div className="action-grid"><button className="primary" onClick={()=>go("book")}><Gift/>Book the Grinch</button><button className="red-button" onClick={()=>go("events")}><CalendarDays/>Events</button></div>
  <section className="photo-card"><HeroCollage/></section>
  <section className="card feature" onClick={()=>go("bored")}><Smile/><div><span className="eyebrow">BORED?</span><h3>Cause a little trouble.</h3><p>Jokes, surprises, coloring ideas and Grinchy fun.</p></div><ChevronRight/></section>
  <section className="card feature"><Heart className="red-icon"/><div><span className="eyebrow">COMMUNITY</span><h3>Jingle Bell Run</h3><p>The Siouxville Grinch proudly supports the Arthritis Foundation Jingle Bell Run.</p></div></section>
  <div className="quick-grid"><button onClick={()=>go("media")}><Newspaper/><b>Media</b></button><button onClick={()=>go("reviews")}><Star/><b>Reviews</b></button><button onClick={()=>go("sponsor")}><Users/><b>Sponsors</b></button></div>
</div>}

function EventsScreen(){return <div className="screen-content"><Header kicker="WHERE'S THE GRINCH?" title="Events & Appearances" text="The app's public calendar will live here — separate from the website and designed for quick mobile viewing."/>
  <section className="calendar-shell card"><div className="calendar-top"><b>SEPTEMBER 2026</b><span>Public appearances</span></div><div className="legend"><span><i className="available"/>Available</span><span><i className="pending"/>Pending</span><span><i className="booked"/>Booked</span></div><div className="empty-calendar"><CalendarDays/><h3>Calendar connection is next.</h3><p>No fake events here. Once the shared event data is connected, confirmed public appearances will populate this screen automatically.</p></div></section>
</div>}

function BookingScreen({go}:{go:(v:View)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const body=`BOOKING REQUEST\n\nName: ${d.get("name")}\nEmail: ${d.get("email")}\nPhone: ${d.get("phone")}\nLocation / Address: ${d.get("location")}\nDuration: ${d.get("duration")}\nRequested Date #1: ${d.get("date1")}\nRequested Time #1: ${d.get("time1")}\nRequested Date #2: ${d.get("date2")}\nRequested Time #2: ${d.get("time2")}\n\nAdditional Details:\n${d.get("details")}`;mail("Siouxville Grinch Booking Request",body)}return <div className="screen-content"><Header kicker="CAUSE SOME HOLIDAY CHAOS" title="Book the Grinch" text={`Send a booking request to ${EMAIL}. The form stays in the app; your email app handles the final send for this test build.`}/><button className="price-strip" onClick={()=>go("pricing")}><BadgeDollarSign/><span><b>See Pricing</b><small>15 minutes through 4 hours</small></span><ChevronRight/></button>
<form className="form-card card" onSubmit={submit}><label>Name *<input name="name" required/></label><label>Email *<input name="email" type="email" required/></label><label>Phone Number *<input name="phone" required/></label><label>Location / Address *<input name="location" required/></label><label>Duration *<select name="duration" required defaultValue=""><option value="" disabled>Select duration</option><option>15 Minutes</option><option>30 Minutes</option><option>45 Minutes</option><option>60 Minutes</option><option>2 Hours</option><option>3 Hours</option><option>4 Hours</option><option>Over 4 Hours / Negotiable</option></select></label><div className="two"><label>Requested Date #1 *<input name="date1" type="date" required/></label><label>Requested Time #1 *<input name="time1" type="time" required/></label></div><div className="two"><label>Requested Date #2<input name="date2" type="date"/></label><label>Requested Time #2<input name="time2" type="time"/></label></div><label>Additional Details *<textarea name="details" maxLength={2000} rows={6} required placeholder="Tell the Grinch what you're plotting..."/></label><button className="primary wide" type="submit"><Send/>Prepare Booking Email</button></form></div>}

function MessagesScreen(){const sayings=useMemo(()=>["Holiday cheer? Suspicious. I'll investigate.","I'm checking the naughty list. Some of you are making this way too easy.","Tell Santa I was nowhere near those presents.","Your complaint has been filed directly into the fireplace."],[]);const [i,setI]=useState(0);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mail("Message for The Siouxville Grinch",`MESSAGE FOR THE GRINCH\n\nFrom: ${d.get("name")}\nReply email: ${d.get("email")||"Not provided"}\n\n${d.get("message")}`)}return <div className="screen-content"><Header kicker="DIRECT FROM SIOUXVILLE" title="Message the Grinch" text="Ask a question, report naughty behavior, or send the mean green guy a message."/><button className="quote card" onClick={()=>setI((i+1)%sayings.length)}><MessageCircle/><div><small>THE GRINCH SAYS</small><strong>“{sayings[i]}”</strong><span>Tap for another</span></div></button><form className="form-card card" onSubmit={submit}><label>Your name *<input name="name" required/></label><label>Email for a reply<input name="email" type="email"/></label><label>Your message *<textarea name="message" required rows={7} placeholder="Dear Grinch..."/></label><button className="primary wide"><Mail/>Prepare Message</button></form></div>}

function About(){return <div className="screen-content"><Header kicker="THE MEAN GREEN GUY" title="About the Siouxville Grinch"/><section className="card story"><p>My name is Martin Dalcourt. I was born and raised in Toronto, Ontario, moved to Sioux City in 2005, and eventually made my way to Sioux Falls in 2025.</p><p>My creative spark kicked in around 2015 with my first custom-made costume, which came out during events with Monster Karaoke & DJ Services. Early appearances included local daycares and family events.</p><p>By 2019, bookings were growing. In 2021, I upgraded the suit and began using prosthetic masks, and the Grinch appearances have continued growing ever since.</p><p>Christmas is for joy and laughs — and when the Siouxville Grinch is around, there may be a prank or two up his sleeve.</p></section></div>}
function Pricing(){const rows=[["15 Minutes","$50"],["30 Minutes","$100"],["45 Minutes","$150"],["60 Minutes","$200"],["2 Hours","$400"],["3 Hours","$600"],["4 Hours","$800"]];return <div className="screen-content"><Header kicker="PRICING & PAYMENT" title="Choose Your Chaos" text="Anything over four hours is negotiable."/><section className="price-list card">{rows.map(r=><div key={r[0]}><b>{r[0]}</b><strong>{r[1]}</strong></div>)}</section><section className="card"><h3>Payment</h3><p>Cash is king. PayPal can be used for Visa/Mastercard payments. Checks are not accepted.</p></section></div>}
function Bored(){return <div className="screen-content"><Header kicker="BORED?" title="Pick Your Mischief" text="A mobile home for the fun side of Siouxville."/><div className="tile-grid"><Fun icon={<Sparkles/>} title="Surprise Me" text="Random Grinch joke or challenge"/><Fun icon={<Camera/>} title="TikTok Pics" text="Photo fun and poses"/><Fun icon={<PartyPopper/>} title="Color a Grinch" text="Coloring activities"/><Fun icon={<Users/>} title="Our Friends" text="Community partners"/><Fun icon={<Images/>} title="Photo Gallery" text="Grinch sightings"/><Fun icon={<Gift/>} title="Advent Calendar" text="Daily holiday mischief"/></div></div>}
function Media(){return <div className="screen-content"><Header kicker="IN THE WILD" title="Media Articles" text="The Siouxville Grinch has been spotted by local media across the region."/><section className="card media-list">{["Sioux City Journal · 2023","KCAU · 2024","KTIV · 2025","KXRB · 2025","Pigeon605 · 2025","MCS · 2026"].map(x=><div key={x}><Newspaper/><b>{x}</b></div>)}</section></div>}
function Reviews(){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);mail("Siouxville Grinch Review",`GRINCHMAS REVIEW\n\nName: ${d.get("name")}\nRating: ${d.get("rating")}/5\n\n${d.get("review")}`)}return <div className="screen-content"><Header kicker="JUDGING THE MEAN GREEN GUY" title="Grinchmas Reviews" text="Be among the first to leave a review through the app."/><form className="form-card card" onSubmit={submit}><label>Name<input name="name" required/></label><label>Rating<select name="rating" defaultValue="5"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Review<textarea name="review" required rows={6}/></label><button className="primary wide"><Star/>Prepare Review</button></form></div>}
function Sponsor(){return <div className="screen-content"><Header kicker="BECOME A SPONSOR" title="Partner with the Grinch" text="Sponsorships help bring more holiday magic to Sioux Falls and beyond."/><section className="card"><HandHeart/><h3>Businesses, creators & community supporters</h3><p>Support events, appearances, and community projects — or pitch a partnership of your own.</p><button className="primary wide top-gap" onClick={()=>mail("Siouxville Grinch Sponsorship Inquiry","SPONSORSHIP INQUIRY\n\nName / Business:\nPhone:\n\nTell us what you have in mind:\n")}><Mail/>Contact About Sponsorship</button></section></div>}
function More({go}:{go:(v:View)=>void}){const items:[[any,string,string,View]]|any=[[Info,"About","Meet Martin and the story behind the Grinch.","about"],[BadgeDollarSign,"Pricing","Appearance pricing and payment options.","pricing"],[Smile,"Bored?","Jokes, activities and Grinchy distractions.","bored"],[Newspaper,"Media","Press coverage and Grinch sightings.","media"],[Star,"Reviews","Judge the mean green guy.","reviews"],[Users,"Sponsorship","Partner with the Siouxville Grinch.","sponsor"]];return <div className="screen-content"><Header kicker="MORE MISCHIEF" title="Explore Siouxville" text="Everything here lives inside the app — no website detours."/><div className="more-list">{items.map(([Icon,title,text,v]:any)=><button className="more-card card" key={title} onClick={()=>go(v)}><Icon/><div><h3>{title}</h3><p>{text}</p></div><ChevronRight/></button>)}</div><div className="contact-line"><Mail/> {EMAIL}</div></div>}
function Header({kicker,title,text}:{kicker:string,title:string,text?:string}){return <header className="page-heading"><span className="eyebrow">{kicker}</span><h2>{title}</h2>{text&&<p>{text}</p>}</header>}
function Fun({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <button className="fun-tile">{icon}<b>{title}</b><small>{text}</small></button>}

export default function Page(){const [view,setView]=useState<View>("home");const tab:Tab=(["home","events","book","messages","more"] as View[]).includes(view)?view as Tab:"more";const go=(v:View)=>{setView(v);window.scrollTo({top:0,behavior:"smooth"})};let content:React.ReactNode;switch(view){case"events":content=<EventsScreen/>;break;case"book":content=<BookingScreen go={go}/>;break;case"messages":content=<MessagesScreen/>;break;case"more":content=<More go={go}/>;break;case"about":content=<About/>;break;case"pricing":content=<Pricing/>;break;case"bored":content=<Bored/>;break;case"media":content=<Media/>;break;case"reviews":content=<Reviews/>;break;case"sponsor":content=<Sponsor/>;break;default:content=<HomeScreen go={go}/>}
const nav=[ ["home","Home",Home],["events","Events",CalendarDays],["book","Book",Gift],["messages","Message",MessageCircle],["more","More",Menu] ] as const;return <main className="app-shell"><header className="top-bar"><span className="brand-dot"/><span>THE SIOUXVILLE GRINCH</span><span className="version">v0.3</span></header><div className="screen">{content}</div><nav className="bottom-nav">{nav.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>go(id)}><Icon/><span>{label}</span></button>)}</nav></main>}
